In [2]:
pip install otter-grader

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: otter-grader in c:\users\sacob\appdata\roaming\python\python313\site-packages (7.0.0)
Requirement already satisfied: click<9.0.0,>=8.1.7 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (8.2.1)
Requirement already satisfied: dill>=0.3.0 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (0.4.0)
Requirement already satisfied: fica>=0.4.1 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from otter-grader) (0.4.1)
Requirement already satisfied: ipylab<2.0.0,>=1.0.0 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from otter-grader) (1.1.0)
Requirement already satisfied: ipython in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from otter-grader) (8.18.1)
Requirement already satisfied: ipywidgets<9.0.0,>=8.1.5 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (8.1.7)
Requirement already satisfied: jinja2<4.0,>=3.1 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (3.1.6)
Requirement already satisfied: jupytext<2.0.0,>=1.19.3 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from otter-grader) (1.19.5)
Requirement already satisfied: nbconvert>=6.0.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (7.16.6)
Requirement already satisfied: nbformat>=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (5.10.4)
Requirement already satisfied: pandas>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (2.3.3)
Requirement already satisfied: python-frontmatter<2.0.0,>=1.3.0 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from otter-grader) (1.3.0)
Requirement already satisfied: python-on-whales<1.0.0,>=0.72.0 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from otter-grader) (0.81.0)
Requirement already satisfied: pyyaml<7,>=6 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (6.0.3)
Requirement already satisfied: requests<3.0,>=2.31 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (2.32.5)
Requirement already satisfied: wrapt<2.0.0,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from otter-grader) (1.17.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9.0.0,>=8.1.7->otter-grader) (0.4.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (5.15.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (3.0.15)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2<4.0,>=3.1->otter-grader) (3.0.2)
Requirement already satisfied: markdown-it-py>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupytext<2.0.0,>=1.19.3->otter-grader) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from jupytext<2.0.0,>=1.19.3->otter-grader) (0.5.0)
Requirement already satisfied: packaging in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from jupytext<2.0.0,>=1.19.3->otter-grader) (26.2)
Requirement already satisfied: pydantic!=2.0.*,<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from python-on-whales<1.0.0,>=0.72.0->otter-grader) (2.12.4)
Requirement already satisfied: typing-extensions in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from python-on-whales<1.0.0,>=0.72.0->otter-grader) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.31->otter-grader) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.31->otter-grader) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.31->otter-grader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.31->otter-grader) (2025.11.12)
Requirement already satisfied: docutils in c:\programdata\anaconda3\lib\site-packages (from fica>=0.4.1->otter-grader) (0.21.2)
Requirement already satisfied: sphinx in c:\programdata\anaconda3\lib\site-packages (from fica>=0.4.1->otter-grader) (8.2.3)
Requirement already satisfied: decorator in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (5.3.1)
Requirement already satisfied: jedi>=0.16 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (0.2.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (2.20.0)
Requirement already satisfied: stack-data in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from ipython->otter-grader) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from prompt-toolkit<3.1.0,>=3.0.41->ipython->otter-grader) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from jedi>=0.16->ipython->otter-grader) (0.8.7)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext<2.0.0,>=1.19.3->otter-grader) (0.1.2)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (6.3.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (0.7.1)
Requirement already satisfied: jupyter-core>=4.7 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (5.8.1)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (1.5.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (1.4.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from jupyter-core>=4.7->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (4.4.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core>=4.7->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (311)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (8.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (2.9.0.post0)
Requirement already satisfied: pyzmq>=23.0 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\x64\cp313 (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\x64\cp3 (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (6.5.7)
Requirement already satisfied: playwright in c:\users\sacob\appdata\roaming\python\python313\site-packages (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (1.63.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.0.0->otter-grader) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.0.0->otter-grader) (4.25.0)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (0.28.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->otter-grader) (2.3.5)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->otter-grader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->otter-grader) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (2.5)
Requirement already satisfied: pyee<14,>=13 in c:\users\sacob\appdata\roaming\python\python313\site-packages (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in c:\programdata\anaconda3\lib\site-packages (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (3.2.4)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.0.0)
Requirement already satisfied: snowballstemmer>=2.2 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (3.0.1)
Requirement already satisfied: babel>=2.13 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (1.4.1)
Requirement already satisfied: roman-numerals-py>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from sphinx->fica>=0.4.1->otter-grader) (3.1.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from stack-data->ipython->otter-grader) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from stack-data->ipython->otter-grader) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\sacob\appdata\local\programs\positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from stack-data->ipython->otter-grader) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/sacobjloan/eds220-hwk1]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

Data set contains coral surveys in the Western Indian Ocean from 1001 sites in 6 ecoregions, documenting how many genera are found at each survey site and distinguishing them as massive, branching, or Porites rus.

McClanahan, T. (2023). Western Indian Ocean Coral Diversity[Data set].
https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [ ]:
import pandas as pd # Reads in pandas package
coral_div = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Ae7d12a5a-f1a9-4a3e-aaa5-5222f67e799d')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [ ]:
#a
rows = coral_div.shape[0] # Stores first value of tibble into rows variable
columns = coral_div.shape[1] # Stores second value of tibble into columns variable

In [10]:
grader.check("q3_a")

q3_a results: All test cases passed!

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [11]:
#b
coral_div_columns = coral_div.columns

In [12]:
grader.check("q3_b")

q3_b results: All test cases passed!

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [13]:
#c
coral_div_types = coral_div.dtypes

In [14]:
grader.check("q3_c")

q3_c results: All test cases passed!

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [15]:
#d
pd.set_option("display.max_columns", None)
first_8_rows = coral_div.head(8)

In [16]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,41,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.592692,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,49,0.021358,54.935499,0.001744,4.7540,2.857747,35.106329,0,2.645199,1150.677856,1.783333,0.333333,30.265219,-0.795494,27.525,0.656533,3224.024414,0.561659,0.10500,0.512126,19.634828,8.2185,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [17]:
grader.check("q3_d")

q3_d results: All test cases passed!

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [ ]:
# e

coral_div.dtypes # Displays the type of each column
coral_div.nunique() # Displays number of unique values in each column
coral_div.info() # Displays number of non-null unique values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PU_ID                575 non-null    int64
 1   PU_Lat               575 non-null    float64
 2   PU_Lon               575 non-null    float64
 3   Number_of_genera     575 non-null    int64
 4   Country              575 non-null    object
 5   Ecoregion            575 non-null    object
 6   Management           575 non-null    object
 7   Habitat              530 non-null    object
 8   Observer             575 non-null    object
 9   Depth                575 non-null    float64
 10  Coralcover           575 non-null    int64
 11  SSTRateofRise        575 non-null    float64
 12  PARmax               575 non-null    float64
 13  Calcite              575 non-null    float64
 14  Dis_oxygen           575 non-null    float64
 15  mean.waveNRJ         575 non-null    float64
 16  Salinity_mean        575 non-null    float64
 17  andrello_reef_value  575 non-null    int64
 18  andrello_nutrients   575 non-null    float64
 19  mean.npp             575 non-null    float64
 20  TT_market_hrs        575 non-null    float64
 21  TT_pop_hrs           575 non-null    float64
 22  cumDHW               575 non-null    float64
 23  SST_Kurtosis         575 non-null    float64
 24  SST_Median           575 non-null    float64
 25  ChlorA_median        575 non-null    float64
 26  andrello_sediments   575 non-null    float64
 27  Current_vel_mean     567 non-null    float64
 28  Diff_attenuation     575 non-null    float64
 29  Grav_NP              575 non-null    float64
 30  Grav_NC              575 non-null    float64
 31  PH                   575 non-null    float64
 32  SST_bimodality       575 non-null    float64
 33  SST_Skewness         575 non-null    float64
 34  ClimateStressModel   575 non-null    float64
 35  Netflow              575 non-null    float64
 36  Indegree             575 non-null    float64
 37  Outdegree            575 non-null    float64
 38  Retention            575 non-null    float64
 39  min_yr               575 non-null    int64
 40  max_yr               575 non-null    int64
 41  no_replicates        575 non-null    int64
dtypes: float64(30), int64(7), object(5)
memory usage: 188.8+ KB

array(['Tanzania', 'Mozambique', 'Kenya', 'Reunion', 'Comoros', 'Mayotte', 'French Southern Territories', 'Madagascar', 'Seychelles', 'South Africa', 'Mauritius'], dtype=object)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

int64 is integer values, while float64 are values with decimals.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

coral_div['Country'] will return the column that describes which country each coral reef is located
coral_div['Country'].unique() will return the unique values that can be found in the Country column

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [ ]:
unique_observers = coral_div['Observer'].nunique() # First the column is indexed, then the number of unique values are called.
coral_div['Coralcover']>=50

0      False
1      False
2      False
3      False
4      False
       ...
570    False
571    False
572    False
573    False
574    False
Name: Coralcover, Length: 575, dtype: bool

In [30]:
grader.check("q6")

q6 results: All test cases passed!

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

It is a pandas series of trues and falses for each row of data in the data frame. Each true is a row that contains data where the Coralcover column is greater than 50, and each false is a row where the Coralcover is equal to or less than 50.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

It is selecting all rows where the Coralcover column is greater than 50.

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [36]:
coral_cover = coral_div[(coral_div['Coralcover'] == 30)&(coral_div['Country'] == 'Tanzania')]

In [ ]:
# View the dataframe
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,30,0.015676,52.992001,0.037043,4.7580,5.885771,35.099083,1156,1.507334,958.495666,0.950000,0.550000,30.656667,-0.940944,27.362500,0.225574,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,30,0.015599,52.992001,0.037043,4.7580,5.285148,35.099083,1156,1.507334,968.100098,0.950000,0.550000,30.021056,-0.942581,27.360000,0.217308,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
122,867,39.368664,-4.656797,23,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.666667,30,0.019138,54.446501,0.001744,4.7110,3.910353,35.137687,393,2.272863,973.582092,1.783333,0.333333,24.709971,-0.770055,27.210000,0.733985,3969.175781,0.763393,0.1165,0.021011,70.412808,8.215,0.448886,-0.036279,0.727025,0.629931,43.50,47.00,53.25,2014,2021,3
123,867,39.368664,-4.656797,26,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.000000,30,0.019138,54.446501,0.001744,4.7110,3.910353,35.137687,393,2.272863,973.582092,1.783333,0.333333,24.709971,-0.770055,27.210000,0.733985,3969.175781,0.763393,0.1165,0.021011,70.412808,8.215,0.448886,-0.036279,0.727025,0.629931,43.50,47.00,53.25,2012,2012,1
124,868,39.391121,-4.656797,24,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,4.000000,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2011,2011,2
125,868,39.391121,-4.656797,20,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.187500,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2014,2021,8
126,868,39.391121,-4.656797,22,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,4.000000,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2016,2019,3
127,872,39.436037,-4.679331,22,Kenya,East African Coral Coast,Restricted,Slope,Tim,29.000000,30,0.018396,54.683998,0.000140,4.7130,4.377082,34.970097,62,1.823716,946.795227,1.750000,0.283333,24.045726,-0.784624,26.776667,0.316760,1916.254883,0.234075,0.0700,0.063383,72.654408,8.214,0.451827,-0.035988,0.628700,0.629931,43.50,47.00,53.25,2009,2009,1
139,1186,55.246386,-21.012018,19,Reunion,Mascarene Islands,Restricted,NaN,Mireille,2.500000,30,0.024752,55.993999,0.000101,4.7390,37.335079,35.131153,14635,0.000000,555.469055,0.550000,0.066667,68.881183,-1.242937,25.700000,0.103709,0.000000,0.028523,0.0360,1.710044,128.876252,8.271,0.568952,-0.009900,0.212200,-0.055715,11.75,14.00,36.00,2005,2005,1
210,2377,49.968784,-15.717807,15,Madagascar,Western and Northern Madagascar,Fished,NaN,Tim,8.500000,30,0.019783,52.161999,0.000384,4.6080,2.077716,34.964661,0,0.004356,2638.477295,8.450000,0.033333,51.258121,-1.283946,26.680000,1.680361,57.260605,0.096964,0.1720,1.724709,0.802782,8.233,0.596164,-0.153239,0.470300,0.349270,18.50,89.00,33.75,2005,2005,1
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018789,53.858002,0.002154,4.7170,3.129188,35.120766,0,1.233231,996.539490,1.216667,0.266667,23.736330,-0.779552,27.245000,0.470832,1746.570435,0.653534,0.1210,0.004043,42.349168,8.216,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,30,0.018789,53.937000,0.001265,4.7195,2.233872,35.125887,0,1.233231,1018.213928,1.550000,0.566667,23.736330,-0.779552,27.250000,0.462739,1746.570435,0.653883,0.1115,0.000879,25.914153,8.216,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,30,0.018462,54.015999,0.000377,4.7220,0.179306,35.131008,0,1.233231,1071.519775,1.550000,0.566667,23.285391,-0.784669,27.260000,0.469467,1746.570435,0.654233,0.1020,0.000879,25.914153,8.216,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018270,53.937000,0.002104,4.7220,2.600268,35.174747,0,0.611645,965.657349,1.733333,0.800000,24.659219,-0.792062,27.255000,0.339959,858.381897,0.738552,0.0960,0.000426,20.656527,8.216,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,30,0.016549,53.943001,0.000076,4.7270,0.034857,34.968960,345,0.063687,980.656921,1.550000,0.700000,27.144278,-0.941926,27.215000,0.212634,23.135084,0.234671,0.0620,0.038530,3.044183,8.213,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.715000,0.158397,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.710000,0.224526,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [37]:
grader.check("q8")

q8 results: All test cases passed!

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [42]:
filtered_data = coral_div[['PH', 'Salinity_mean','Depth']]

In [43]:
# View the dataframe
filtered_data.head()

       PH  Salinity_mean  Depth
0  8.2175      35.167646   11.0
1  8.2175      35.167646    2.0
2  8.2175      35.167646    4.0
3  8.2175      35.167646    3.0
4  8.2180      35.102688    1.5

In [44]:
grader.check("q9")

q9 results: All test cases passed!

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [60]:
sampling_2017 = coral_div[['PH', 'Salinity_mean', 'Depth','max_yr']]
sampling_2017 = sampling_2017[sampling_2017['max_yr'] == 2017]

In [61]:
# View the dataframe 
sampling_2017

         PH  Salinity_mean      Depth  max_yr
67   8.2150      35.100085  16.000000    2017
68   8.2145      35.144927  10.000000    2017
70   8.2150      35.101086  11.000000    2017
71   8.2150      35.101086  11.000000    2017
72   8.2150      35.101086   9.000000    2017
73   8.2150      35.101086   9.000000    2017
84   8.2110      35.278084  12.500000    2017
85   8.2110      35.278084   6.000000    2017
164  8.2220      35.337914   9.875000    2017
167  8.2220      35.337914  12.075000    2017
169  8.2220      35.337914  10.300000    2017
172  8.2220      35.337914  11.000000    2017
174  8.2225      35.287419   7.266667    2017
176  8.2225      35.287419  13.225000    2017
179  8.2225      35.287419  10.550000    2017
182  8.2220      35.331669  12.033333    2017
185  8.2230      35.374460  10.900000    2017
188  8.2230      35.374460  14.725000    2017
191  8.2230      35.247482   9.725000    2017
194  8.2230      35.341358  11.075000    2017
197  8.2230      35.390354  10.600000    2017
346  8.2165      35.114244   7.000000    2017
347  8.2165      35.112398   3.000000    2017
348  8.2165      35.112398   4.000000    2017
349  8.2160      35.117374   5.500000    2017
350  8.2160      35.117374   2.000000    2017
351  8.2160      35.117374  15.000000    2017
352  8.2160      35.117374   5.000000    2017
353  8.2165      35.149462  11.000000    2017
354  8.2160      35.270199   9.000000    2017
395  8.2400      35.276642   9.416667    2017
559  8.2120      35.204185   1.500000    2017
566  8.2400      35.301208  17.000000    2017
569  8.2400      35.301208  13.833333    2017
574  8.2400      35.301208  13.470000    2017

In [62]:
grader.check("q10")

q10 results: All test cases passed!

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [ ]:
subset = coral_div.iloc[95:101,[16,19,27]]

In [71]:
# View the dataframe
subset

     Salinity_mean     mean.npp  Current_vel_mean
95       35.201630  1365.146729          0.878417
96       35.204185  1117.635010          0.839372
97       35.234774  1105.270142          0.685955
98       35.234774  1105.270142          0.685955
99       35.250068  1082.196411               NaN
100      35.250068  1082.196411               NaN

In [66]:
grader.check("q11")

q11 results: All test cases passed!

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

The code populates the dataframe with trues and falses, trues where a cell has nan and false where a cell has a numeric value.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

This code checks each column for any missing values, and if there are 0 cells with missing values in a column it will be assigned false. If there are ANY cells with missing values in a column,it will be assigned true. Essentially it summarizes which columns are missing data and which aren't.

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [72]:
subset_na = subset[subset['Current_vel_mean'].isna()]

In [73]:
# View the dataframe 
subset_na

     Salinity_mean     mean.npp  Current_vel_mean
99       35.250068  1082.196411               NaN
100      35.250068  1082.196411               NaN

In [74]:
grader.check("q14")

q14 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [75]:
grader.check_all()

q10 results: All test cases passed!

q11 results: All test cases passed!

q14 results: All test cases passed!

q3_a results: All test cases passed!

q3_b results: All test cases passed!

q3_c results: All test cases passed!

q3_d results: All test cases passed!

q6 results: All test cases passed!

q8 results: All test cases passed!

q9 results: All test cases passed!